version: "3"

services:
  chainhammer:
    image: silesiacoin/chainhammer:v0.04
    entrypoint: ["bash", "-c"]
    volumes:
    - ./experiments:/var/app/chainhammer/experiments
    - ./hammer:/var/app/chainhammer/hammer
    - ./logs:/var/app/chainhammer/logs
    command:
      - CH_TXS=1000 CH_THREADING="threaded2 300" ./run.sh multinet-TestRPC testrpc
    networks:
      hammer:
        aliases:
          - hammer.localhost

networks:
    hammer:
        driver: bridge
