version: "3"

services:
  chainhammer:
    image: silesiacoin/chainhammer:v0.04
    entrypoint: ["bash", "-c"]
    volumes:
    - ./experiments:/var/app/chainhammer/experiments
    command:
      - CH_TXS=3000 CH_THREADING="threaded2 1000" ./run.sh multinet-TestRPC testrpc
    networks:
      hammer:
        aliases:
          - hammer.localhost

networks:
    hammer:
        driver: bridge
